[versions]
asm = "9.9.1"
findbugs = "3.0.2"
gradleToolingApi = "8.10"
gson = "2.8.5"
guava = "23.2-jre"
junit = "4.12"
lombok = "1.18.30"
okhttp = "3.14.9"
slf4jSimple = "1.7.10"
undercouchDownload = "5.7.0"

[libraries]
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
findbugs-jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "findbugs" }
gradle-tooling-api = { module = "org.gradle:gradle-tooling-api", version.ref = "gradleToolingApi" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { module = "junit:junit", version.ref = "junit" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4jSimple" }

[plugins]
undercouch-download = { id = "de.undercouch.download", version.ref = "undercouchDownload" }
